@server = http://localhost:4654 
@access = /api/v1/shop 
@teams = /api/v1/teams 
@tournament = /api/v1/tournament
@season = /api/v1/seasons
@rounds = /api/v1/rounds
@api = /api/v1
@common = /api/v1/football


### 
GET {{server}}{{common}}/1/season/56953/match/update

### 
POST {{server}}{{common}}/133/season/57114/season/update 
Content-Type: application/json

{
    "channel": "UCoqrrrfDpWOgdqw1vRoiG_A", 
    "playlist": "PL0fNrAOa7mzDrQy1xs3MsjgoUjAtefX7F"
}



# unique-tournament/17/season/52186
# unique-tournament/8/season/52376
# unique-tournament/23/season/52760
# unique-tournament/34/season/52571
#35/52608
//7/52162
//1/56953
//133/57114